/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Classes.GerenciaJanelas;
import Classes.GerenciaUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author mfm65
 */
public class Entrar extends javax.swing.JFrame {
    private char senhaEchoChar;
            
    public Entrar() {
        initComponents();
        senhaEchoChar = inputSenha.getEchoChar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        esquerda = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        linhaInputNome = new javax.swing.JPanel();
        inputSenha = new javax.swing.JPasswordField();
        linhaInputSenha = new javax.swing.JPanel();
        mostrarSenha = new javax.swing.JCheckBox();
        iconeMostrarSenha = new javax.swing.JLabel();
        cadastroLabel2 = new javax.swing.JLabel();
        cadastroLabel = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        direita = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        esquerda.setBackground(new java.awt.Color(18, 18, 18));

        titulo.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 102));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Login");

        nome.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        nome.setForeground(new java.awt.Color(102, 102, 102));
        nome.setText("Nome:");

        senha.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        senha.setForeground(new java.awt.Color(102, 102, 102));
        senha.setText("Senha:");

        inputNome.setBackground(new java.awt.Color(18, 18, 18));
        inputNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputNome.setForeground(new java.awt.Color(255, 255, 255));
        inputNome.setBorder(null);
        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        linhaInputNome.setBackground(new java.awt.Color(51, 51, 51));
        linhaInputNome.setPreferredSize(new java.awt.Dimension(10, 2));

        javax.swing.GroupLayout linhaInputNomeLayout = new javax.swing.GroupLayout(linhaInputNome);
        linhaInputNome.setLayout(linhaInputNomeLayout);
        linhaInputNomeLayout.setHorizontalGroup(
            linhaInputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaInputNomeLayout.setVerticalGroup(
            linhaInputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        inputSenha.setBackground(new java.awt.Color(18, 18, 18));
        inputSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputSenha.setForeground(new java.awt.Color(255, 255, 255));
        inputSenha.setBorder(null);

        linhaInputSenha.setBackground(new java.awt.Color(51, 51, 51));
        linhaInputSenha.setPreferredSize(new java.awt.Dimension(10, 2));

        javax.swing.GroupLayout linhaInputSenhaLayout = new javax.swing.GroupLayout(linhaInputSenha);
        linhaInputSenha.setLayout(linhaInputSenhaLayout);
        linhaInputSenhaLayout.setHorizontalGroup(
            linhaInputSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaInputSenhaLayout.setVerticalGroup(
            linhaInputSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        mostrarSenha.setForeground(new java.awt.Color(102, 102, 102));
        mostrarSenha.setText("Mostrar Senha");
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });

        iconeMostrarSenha.setIcon(new javax.swing.ImageIcon("C:\\imagensCursoUdemyJava\\Projeto 02\\exibirSenha.png")); // NOI18N

        cadastroLabel2.setForeground(new java.awt.Color(102, 102, 102));
        cadastroLabel2.setText("Não possui uma conta?");

        cadastroLabel.setForeground(new java.awt.Color(204, 204, 255));
        cadastroLabel.setText("Cadastre-se");
        cadastroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroLabelMouseClicked(evt);
            }
        });

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout esquerdaLayout = new javax.swing.GroupLayout(esquerda);
        esquerda.setLayout(esquerdaLayout);
        esquerdaLayout.setHorizontalGroup(
            esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(esquerdaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(esquerdaLayout.createSequentialGroup()
                        .addGroup(esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(linhaInputNome, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(senha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNome)
                            .addComponent(linhaInputSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                        .addGap(134, 134, 134))
                    .addGroup(esquerdaLayout.createSequentialGroup()
                        .addGroup(esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(esquerdaLayout.createSequentialGroup()
                                .addComponent(iconeMostrarSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarSenha))
                            .addGroup(esquerdaLayout.createSequentialGroup()
                                .addComponent(cadastroLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadastroLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(esquerdaLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        esquerdaLayout.setVerticalGroup(
            esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esquerdaLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linhaInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linhaInputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroLabel2)
                    .addComponent(cadastroLabel))
                .addGap(44, 44, 44)
                .addGroup(esquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeMostrarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarSenha))
                .addGap(55, 55, 55)
                .addComponent(confirmar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        direita.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\imagensCursoUdemyJava\\Projeto 02\\login2.png")); // NOI18N

        javax.swing.GroupLayout direitaLayout = new javax.swing.GroupLayout(direita);
        direita.setLayout(direitaLayout);
        direitaLayout.setHorizontalGroup(
            direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, direitaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        direitaLayout.setVerticalGroup(
            direitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, direitaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(direita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(direita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        if(mostrarSenha.isSelected()){
            iconeMostrarSenha.setIcon(new javax.swing.ImageIcon("C:\\imagensCursoUdemyJava\\Projeto 02\\ocultarSenha.png"));
            inputSenha.setEchoChar('\u0000');
            mostrarSenha.setText("Ocultar Senha");
        } else {
            iconeMostrarSenha.setIcon(new javax.swing.ImageIcon("C:\\imagensCursoUdemyJava\\Projeto 02\\exibirSenha.png"));
            inputSenha.setEchoChar(senhaEchoChar);
            mostrarSenha.setText("Mostrar Senha");
        }
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void cadastroLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroLabelMouseClicked
        GerenciaJanelas.cadastro(this);
    }//GEN-LAST:event_cadastroLabelMouseClicked

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        if (inputNome.getText().equals("") || inputSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Existe campos que não foram preenchidos!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else {
            String nome = inputNome.getText();
            String senha = inputSenha.getText();

            boolean parametro = GerenciaUsuarios.verificaUsuario(nome, senha);
            
            if(parametro == true){
                JOptionPane.showMessageDialog(null, "Logado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                GerenciaJanelas.telaPrincipal(this, inputNome.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Conta não encontrada!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastroLabel;
    private javax.swing.JLabel cadastroLabel2;
    private javax.swing.JButton confirmar;
    private javax.swing.JPanel direita;
    private javax.swing.JPanel esquerda;
    private javax.swing.JLabel iconeMostrarSenha;
    private javax.swing.JTextField inputNome;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel linhaInputNome;
    private javax.swing.JPanel linhaInputSenha;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
