/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package FramesInternos;

import Classes.Chamados;
import javax.swing.JOptionPane;

/**
 *
 * @author mfm65
 */
public class CadastroChamado extends javax.swing.JInternalFrame {
    
    public CadastroChamado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        numeroDaMaquina = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        inputNumeroMaquina = new javax.swing.JTextField();
        linhaInputNumeroMaquina = new javax.swing.JPanel();
        inputNome = new javax.swing.JTextField();
        linhaInputNome = new javax.swing.JPanel();
        numeroDaMaquina1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescricao = new javax.swing.JTextPane();
        Confirmar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastre um chamado");

        fundo.setBackground(new java.awt.Color(40, 42, 58));

        titulo.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 204, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Informações");

        numeroDaMaquina.setBackground(new java.awt.Color(0, 0, 0));
        numeroDaMaquina.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        numeroDaMaquina.setForeground(new java.awt.Color(204, 204, 255));
        numeroDaMaquina.setText("Numero da máquina:");

        nome.setBackground(new java.awt.Color(0, 0, 0));
        nome.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        nome.setForeground(new java.awt.Color(204, 204, 255));
        nome.setText("Informe seu nome:");

        inputNumeroMaquina.setBackground(new java.awt.Color(40, 42, 58));
        inputNumeroMaquina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputNumeroMaquina.setForeground(new java.awt.Color(255, 255, 255));
        inputNumeroMaquina.setBorder(null);
        inputNumeroMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumeroMaquinaActionPerformed(evt);
            }
        });

        linhaInputNumeroMaquina.setBackground(new java.awt.Color(204, 204, 255));
        linhaInputNumeroMaquina.setPreferredSize(new java.awt.Dimension(10, 2));

        javax.swing.GroupLayout linhaInputNumeroMaquinaLayout = new javax.swing.GroupLayout(linhaInputNumeroMaquina);
        linhaInputNumeroMaquina.setLayout(linhaInputNumeroMaquinaLayout);
        linhaInputNumeroMaquinaLayout.setHorizontalGroup(
            linhaInputNumeroMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        linhaInputNumeroMaquinaLayout.setVerticalGroup(
            linhaInputNumeroMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        inputNome.setBackground(new java.awt.Color(40, 42, 58));
        inputNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputNome.setForeground(new java.awt.Color(255, 255, 255));
        inputNome.setBorder(null);
        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        linhaInputNome.setBackground(new java.awt.Color(204, 204, 255));
        linhaInputNome.setPreferredSize(new java.awt.Dimension(10, 2));

        javax.swing.GroupLayout linhaInputNomeLayout = new javax.swing.GroupLayout(linhaInputNome);
        linhaInputNome.setLayout(linhaInputNomeLayout);
        linhaInputNomeLayout.setHorizontalGroup(
            linhaInputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaInputNomeLayout.setVerticalGroup(
            linhaInputNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        numeroDaMaquina1.setBackground(new java.awt.Color(0, 0, 0));
        numeroDaMaquina1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        numeroDaMaquina1.setForeground(new java.awt.Color(204, 204, 255));
        numeroDaMaquina1.setText("Informações Adicionais:");

        inputDescricao.setBackground(new java.awt.Color(40, 42, 58));
        inputDescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(inputDescricao);

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linhaInputNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(inputNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linhaInputNumeroMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(numeroDaMaquina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(inputNumeroMaquina)
                    .addComponent(numeroDaMaquina1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addGap(109, 109, 109))
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDaMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNumeroMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linhaInputNumeroMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(linhaInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numeroDaMaquina1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Confirmar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNumeroMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumeroMaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumeroMaquinaActionPerformed

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        int numeroMaquina = 0;
        String usuario;
        String descricao;
        boolean status = false;
        
        if(inputNome.getText().equals("") || inputNumeroMaquina.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Existe campos que não foram preenchidos!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else if(inputNome.getText().length() > 45){
            JOptionPane.showMessageDialog(null, "Limite de caracteres atingidos!\n\nCampo nome: 45 chars", "Erro!", JOptionPane.ERROR_MESSAGE);
        }  else if(inputDescricao.getText().length() > 50) {
            JOptionPane.showMessageDialog(null, "Limite de caracteres atingidos!\n\nDescricao: 50 chars", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else {
            try{
                numeroMaquina = Integer.parseInt(inputNumeroMaquina.getText());
                usuario = inputNome.getText();
                descricao = inputDescricao.getText();
                
                Chamados chamado = new Chamados(numeroMaquina, usuario, descricao);
                
                status = chamado.registrar();

                if(status){
                    JOptionPane.showMessageDialog(null, "Chamado feito com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário não cadastrado no sistema!", "Erro!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Deve conter um número no campo \"Numero da Maquina\"!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JPanel fundo;
    private javax.swing.JTextPane inputDescricao;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputNumeroMaquina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel linhaInputNome;
    private javax.swing.JPanel linhaInputNumeroMaquina;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numeroDaMaquina;
    private javax.swing.JLabel numeroDaMaquina1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
